spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mb_db
    username: mb_db
    password: mb_db
    testWhileIdle: true
    validationQuery: SELECT 1

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create  # Options: none, validate, update, create, create-drop
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy  # Note: This is now deprecated; use naming strategy in properties block below.

    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect  # Updated to MySQL 8 dialect