spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mb_db
    username: mb_db
    password: mb_db
    testWhileIdle: true
    validationQuery: SELECT 1

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create  # Options: none, validate, update, create, create-drop
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy

    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  batch:
    job:
      enabled: false